Algoritmo "TesteDeVetor"
//
//
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 9/1/2021
Var

   V:vetor[1..10] de inteiro
   C:inteiro

Inicio

   Para C<-1 ate 10 faca
      escreval("Digite o " ,C," o. valor:")
      leia (V[C])
   FimPara

   Para C<-1 ate 10 faca
      escreva("{",V[C],"}")
   FimPara
   
Fimalgoritmo