Algoritmo "semnome"
// 
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 28/12/2020
Var
   ANO_ATUAL,ANO_NASC,IDADE:INTEIRO

Inicio
   escreval("Em que ano estamos? ")
   leia(ANO_ATUAL)
   escreva("Em que ano eu nasci? ")
   leia(ANO_NASC)
   IDADE <- ANO_ATUAL - ANO_NASC
   escreva("Minha idade sera ", IDADE)


Fimalgoritmo